articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list_view, name='articles'),
    path('articles/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.article_detail_view, name='detail')
]

cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('', views.article_manage_list_view, name='manage'),
    path('create/', views.articles_create_view, name='create'),
    path('create_content/', views.create_update_delete_content_view, name='create_content'),
    path('create_image_content/', views.create_update_delete_content_with_file_view, name='create_image_content'),
    path('<slug:slug>/', views.article_manage_detail_view, name='detail'),
]

knowledge_base/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('articles.urls', namespace='articles')),
    path('manage/', include('cms.urls', namespace='cms')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

articles/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.contrib.auth import get_user_model
from django.template.loader import render_to_string
from django.urls import reverse
from pytils.translit import slugify

from articles.auxiliary_functions import create_slug_code
from articles.fields import OrderField


User = get_user_model()


class OnModerationManager(models.Manager):
    """Custom manager for Article where draft == false"""
    def get_queryset(self):
        return super().get_queryset().filter(draft=False)


class Article(models.Model):
    """Article Model"""
    user = models.ForeignKey(User,
                             verbose_name='Автор',
                             on_delete=models.CASCADE,
                             related_name='articles')
    title = models.CharField(verbose_name='Название статьи',
                             max_length=255)
    slug = models.SlugField(max_length=255,
                            unique=True)
    created = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Дата создания', auto_now=True)
    draft = models.BooleanField(default=True)
    objects = models.Manager()
    published = OnModerationManager()

    def save(self, *args, **kwargs):
        """Redefining the method for adding a slug"""
        if not self.slug:
            self.slug = f'{slugify(self.title)}-{create_slug_code(3)}'
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Absolute url for simple viewing"""
        return reverse('articles:detail',
                       args=[self.created.year,
                             self.created.month,
                             self.created.day,
                             self.slug])

    def get_absolute_url_for_manage(self):
        """Absolute url for manage"""
        return reverse('cms:detail',
                       args=[self.slug])

    def get_comment(self):
        """Returns the main comment in the branch"""
        return self.comments.filter(parent__isnull=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        ordering = ['-created']
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Content(models.Model):
    """Model for creating article content"""
    article = models.ForeignKey(Article,
                                related_name='contents',
                                on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType,
                                     on_delete=models.CASCADE,
                                     limit_choices_to={'model__in': (
                                         'text',
                                         'video',
                                         'image',
                                         'file',
                                         'citation',
                                         'title')})
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['article'])

    class Meta:
        ordering = ['order']


class ItemBase(models.Model):
    """
    Abstract class
    Basic content model of article content
    """
    owner = models.ForeignKey(User,
                              related_name='%(class)s_related',
                              on_delete=models.CASCADE,
                              verbose_name='items')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.owner

    def get_type(self):
        """Returns model name"""
        return self._meta.model_name

    def render_to_show(self):
        """Renders a template with one of the content types to display"""
        return render_to_string(f'../../articles/templates/content/{self._meta.model_name}.html',
                                {'item': self})

    def render_to_manage(self):
        """Renders a template with one of the content types to manage"""
        return render_to_string(f'../../cms/templates/content/{self._meta.model_name}.html',
                                {'item': self})


class Title(ItemBase):
    """Extension of the basic content model of the article content that has the title format"""
    content = models.CharField(max_length=255)


class Text(ItemBase):
    """Extension of the basic content model of the article content that has the text format"""
    content = models.TextField()


class File(ItemBase):
    """Extension of the basic content model of the article content that has the file format"""
    file = models.FileField(upload_to='files')


class Image(ItemBase):
    """Extension of the basic content model of the article content that has the image format"""
    file = models.FileField(upload_to='images')


class Video(ItemBase):
    """Extension of the basic content model of the article content that has the url format"""
    url = models.URLField()


class Citation(ItemBase):
    """Extension of the basic content model of the article content that has the citation format"""
    content = models.TextField()
    signature = models.TextField()

comments/models.py
from django.db import models
from django.contrib.auth import get_user_model
from articles.models import Article


User = get_user_model()


class Comment(models.Model):
    """Model for comments to the Article"""
    author = models.ForeignKey(User,
                               verbose_name='Автор',
                               on_delete=models.CASCADE,
                               related_name='comments')
    article = models.ForeignKey(Article,
                                verbose_name='Название статьи',
                                on_delete=models.CASCADE,
                                related_name='comments')
    parent = models.ForeignKey('self',
                               verbose_name='Главный комментарий',
                               on_delete=models.CASCADE,
                               blank=True,
                               null=True,
                               related_name='child_comments')
    message = models.TextField(verbose_name='Коммантарий')
    active = models.BooleanField(default=True,
                                 verbose_name='Активен')

    def __str__(self):
        return f'Комментарий автора {self.author.username}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

articles/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(label=False,
                             widget=forms.TextInput(attrs={'class': "uk-search-input uk-form-large uk-border-rounded",
                                                           'placeholder': "Задайте свой вопрос",
                                                           'autocomplete': "off",
                                                           'data-minchars': "1",
                                                           'type': "search"}))

articles/views.py
from django.shortcuts import render, get_object_or_404
from comments.comment_services import create_comment
from comments.forms import CommentForm
from .models import Article
from .forms import SearchForm
from .article_services import get_articles, get_article_by_search, get_paginator_page, add_or_show_total_views


def article_list_view(request):
    """Returns list articles"""
    form = SearchForm()
    if 'search' in request.GET:
        articles = get_article_by_search(request_search=request.GET)
    else:
        articles = get_articles()
    page = request.GET.get('page')
    articles = get_paginator_page(articles=articles, page=page)
    return render(request,
                  'articles/list.html',
                  {'articles': articles,
                   'page': page,
                   'form': form})


def article_detail_view(request, year, month, day, slug):
    """Details of Article"""
    comment_form = CommentForm()
    article = get_object_or_404(Article,
                                slug=slug,
                                created__year=year,
                                created__month=month,
                                created__day=day)
    if request.method == 'GET':
        total_views = add_or_show_total_views(add=True,
                                              article_id=article.id)
    if request.method == 'POST':
        total_views = add_or_show_total_views(article_id=article.id)
        create_comment(request_data=request.POST,
                       user=request.user,
                       article=article)
    return render(request,
                  'articles/detail.html',
                  {'article': article,
                   'comment_form': comment_form,
                   'total_views': total_views})

articles/templates/articles/create.html
{% extends "base.html" %}

{% block title %}
  Добавление статьи
{% endblock %}
{% block content %}
    <form method="post">
      {{ article_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Добавить статью"></p>
    </form>
{% endblock %}

articles/templates/articles/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ article.title }}
{% endblock %}
{% block content %}
<div class="uk-section uk-section-muted">
  <div class="uk-container">
    <ul class="uk-breadcrumb uk-margin-medium-top-">
      <li><a href="{% url 'articles:articles' %}">Главная</a></li>
      <li><span>{{ article.title }}</span></li>
    </ul>
    <div class="uk-background-default uk-border-rounded uk-box-shadow-small">
      <div class="uk-container uk-container-xsmall uk-padding-large">
        <article class="uk-article">
          <h1 class="uk-article-title">{{ article.title }} ({{ total_views }})</h1>
          <div class="uk-article-meta uk-margin uk-flex uk-flex-middle">
            <img class="uk-border-circle uk-avatar-small" src="https://via.placeholder.com/80x80" alt="Sara Galen">
            <div>
                Добавлeно: {{ article.user.username}}
                {{ article.created.day }}.{{ article.created.month }}.{{ article.created.year }}<br>
                Обновлено: {{ article.updated.day }}.{{ article.updated.month }}.{{ article.updated.year }}
            </div>
          </div>
          {% for content in article.contents.all %}
              {{ content.item.render_to_show }}
          {% endfor %}
        </article>
        <div class="share uk-text-center uk-margin-large-top">
        </div>
        <h2>Комментарии: ({{ article.comments.count }})</h2>
        {% for parent_comment in article.get_comment %}
            <div class="uk-card">
                <div>
                    <img class="uk-avatar uk-border-circle" src="{% static "img/avatar.png" %}" alt="John Brown" />
                </div>
                <div class="comment-margin-left">
                    <h5 class="uk-margin-remove-bottom">{{ parent_comment.author }} {{ parent_comment.id }}</h5>
                    <p class="uk-article-meta uk-margin-xsmall-top">{{ parent_comment.message }}</p>
                </div>
            </div>
            {% if request.user.is_authenticated %}
                <div class="uk-text-right" data-user="{{ parent_comment.author }}" data-id="{{ parent_comment.id }}">
                    <a href="#comment-form" class="uk-button-link">Ответить</a>
                </div>
            {% endif %}
            {% for child_comment in parent_comment.child_comments.all %}
                <div class="uk-card child">
                    <div>
                        <img class="uk-avatar uk-border-circle" src="{% static "img/avatar.png" %}" alt="John Brown" />
                    </div>
                    <div class="comment-margin-left">
                        <h5 class="uk-margin-remove-bottom">{{ child_comment.author }}</h5>
                        <p class="uk-article-meta uk-margin-xsmall-top">{{ child_comment.message }}</p>
                    </div>
                </div>
            {% endfor %}
        {% endfor %}
      </div>
    <div class="uk-container uk-container-xsmall uk-padding-large">
        {% if request.user.is_authenticated %}
            <form class="uk-form-stacked uk-margin-medium-top" method="post" id="comment-form">
                {% csrf_token %}
                <div class="uk-margin-bottom">
                    <input id="comment-id" type="hidden" name="comment_id">
                    <label class="uk-form-label" for="message">Оставьте комментарий:</label>
                    <div class="uk-form-controls">
                        {{ comment_form.message }}
                    </div>
                </div>
                <div class="uk-text-right">
                    <input class="uk-button uk-button-primary uk-border-rounded" type="submit" value="Отправить">
                </div>
            </form>
        {% else%}
            <div class="share uk-text-center uk-margin-large-top">
                <p><a>Войдите</a>, чтобы комментировать</p>
            </div>
        {% endif %}
    </div>
    </div>
  </div>
</div>
{% endblock %}
{% block domready %}
    $(document).on('click', ".uk-button-link", function(event) {
        $('#comment-id').val($(this).parent().data('id'));
        $('#id_message').val($.trim($(this).parent().data('user') + ', ' + ($('#id_message').val())));
    });
{% endblock %}

articles/templates/articles/list.html
{% extends "base.html" %}
{% load articles_tag %}
{% block title %}
  Список статей
{% endblock %}
{% block search %}
<div class="uk-background-primary uk-background-norepeat uk-background-cover uk-background-center-center uk-light">
  <div class="uk-section uk-section-small uk-section-hero uk-position-relative" data-uk-scrollspy="cls: uk-animation-slide-bottom-medium; repeat: true">
    <div class="uk-container">
        <h1 class="uk-text-center uk-margin-remove-top">Чем мы можем помочь Вам?</h1>
        <div class="hero-search uk-margin-bottom">
            <div class="uk-position-relative">
                <form class="uk-search uk-search-default uk-width-1-1">
                    <span data-uk-search-icon="ratio: 1.2"></span>
                    {{ form.as_p }}
                </form>
            </div>
        </div>
    </div>
  </div>
</div>
{% endblock %}
{% block content %}
    {% if articles %}
        {% for article in articles %}
            <div>
              <div class="uk-card uk-card-category uk-card-default uk-card-hover uk-card-body uk-inline uk-border-rounded uk-width-1-1">
                <a class="uk-position-cover" href="{{ article.get_absolute_url }}"></a>
                <h3 class="uk-card-title uk-margin-remove uk-text-primary">{{ article.title }}</h3>
                  <div class="uk-article-meta uk-flex uk-flex-middle">
                  <div>
                    Автор: {{ article.user.username }}
                  </div>
                </div>

                  <div class="uk-article-meta uk-flex uk-flex-middle">
                      Добавлeно: {{ article.created.day }}.{{ article.created.month }}.{{ article.created.year }}<br>
                      Обновлено: {{ article.updated.day }}.{{ article.updated.month }}.{{ article.updated.year }}
                  </div>
                  {% show_post_description article %}
              </div>

            </div>
        {% endfor %}
    {% else %}
        <p>Нет статей, удовлетворяющих запросу</p>
    {% endif %}
    {% include "include/paginator.html" with page=articles %}
{% endblock %}